spring:
  profiles:
    active: @spring.active@
  datasource:
    db1:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.10.93:3306/gjj?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useOldAliasMetadataBehavior=true
      username: gdca
      password: gdca1234

mybatis-plus:
  mapper-locations: classpath*:y/y/yadmin/**/*.xml